service:
  name: Azure Container App Service
  identifier: azure_container_app_service
  tags: {}
  serviceDefinition:
    type: AzureContainerApps
    spec:
      manifests:
        - manifest:
            identifier: aca_manifest
            type: AzureContainerAppsConfiguration
            spec:
              store:
                type: Harness
                spec:
                  files:
                    - /azure-container-apps/manifest
      artifacts:
        primary:
          primaryArtifactRef: <+input>
          sources:
            - identifier: primary_artifact
              spec:
                connectorRef: <+input>
                imagePath: <+input>
                tag: <+input>
              type: DockerRegistry
